### ISSUE TITLE
Custom access token fields

### ISSUE THREAD

**Issue by ghaiklor** [jaredhanson/passport-http-bearer#26]
Hi everyone.

Will great if you create in options properties for set custom names for access_token. We have the problem that when one token is send in headers and secons in query -> bearer is brokes up.

I can create a quick pull request for it.

**Comment by hboylan** [comment]
+1 Passing token in headers would avoid lengthy urls

**Comment by hboylan** [comment]
-1 Actually just found this comment in the /lib/strategy.js
```
 * The HTTP Bearer authentication strategy authenticates requests based on
 * a bearer token contained in the `Authorization` header field, `access_token`
 * body parameter, or `access_token` query parameter.
```

**Comment by mrgamer** [comment]
Nice find @hboylan, [here's the reference](http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html) read at 2.3

Maybe to solve your problem @ghaiklor there must be a different behaviour when receiving 2 tokens; instead changing the query name
