### ISSUE TITLE
Is this project Dead?

### ISSUE THREAD

**Issue by aronrodrigues** [jaredhanson/passport-http-bearer#29]

**Comment by kumavis** [comment]
@jaredhanson happy to maintain if you add as a collab

**Comment by kumavis** [comment]
This module works for me, even if maintainer is absent

**Comment by mrgamer** [comment]
:+1: for having a maintainer, I think @jaredhanson created a ton of projects, but having collaborators is nothing wrong

**Comment by pronebird** [comment]
@jaredhanson if @kumavis is still up for maintenance I would gladly see him in charge as the project is clearly out of date.

**Comment by lesterzone** [comment]
First, thanks!
Then: 
Example not working and docs required. Glad I looked PR first. Very helpful stuff waiting for maintainer!
