### ISSUE TITLE
Optional authorization

### ISSUE THREAD

**Issue by pronebird** [jaredhanson/passport-http-bearer#38]
Is it possible to have endpoints with optional authorization? For example, when if bearer token is provided, we pick the corresponding user for it, if not, we let the next callback in chain to handle that, e.g. no `req.user` initialized. I need it for endpoints on API that return personalized results when user authorized.

**Comment by jaredhanson** [comment]
Use [passport-anonymous](https://github.com/jaredhanson/passport-anonymous)

**Comment by pronebird** [comment]
@jaredhanson thanks I didn't know about that.
