### ISSUE TITLE
is it possible to have a typescript definition file?

### ISSUE THREAD

**Issue by demobiel** [jaredhanson/passport-http-bearer#41]
is it possible to have a typescript definition file?

thanks !

**Comment by jaredhanson** [comment]
No.

**Comment by demobiel** [comment]
ok :)

**Comment by G-Rath** [comment]
@jaredhanson any particular reason why not? Are you against `TypeScript`, or just don't have the time or familiarity to make one yourself?

**Comment by bryan-vh** [comment]
@jaredhanson any update on this? Would be really beneficial to have for people using NestJs with TS.

**Comment by jaredhanson** [comment]
I don't use TypeScript, so I have not interest in spending the time required to maintain and support it.  I believe it is possible to distribute TypeScript definitions external to a project, and there are such definitions for Passport and its strategies.

If someone who is familiar with TypeScript wants to document how to use these, I'd be happy to include that in the README or documentation for others who also use TypeScript.

**Comment by davideicardi** [comment]
Just for info, type definition can be found here: https://www.npmjs.com/package/@types/passport-http-bearer
