### ISSUE TITLE
Allow the ability to change the name of access_token

### ISSUE THREAD

**Issue by switzer** [jaredhanson/passport-http-bearer#5]
Allow the ability to pass in the name of the token field.  This could be done exactly like the local strategy does with the username and password fields, e.g.:

passport.use(new BearerStrategy(
  {accessTokenField: 'api_key'},

**Comment by martinprot** [comment]
Hi.
I agree we should stay with access_token, but you should at least mention it in the documentation, for newbes like me who do not know the RFC.
Anyway, thanks for the module.
